#!/bin/sh -e
export PATH=/sbin:/bin:/usr/sbin:/usr/bin

RESOLVCONF="/etc/resolv.conf"
BACKRESOLV="/etc/resolv.wader.backup"
WADERCONN="/tmp/wader-conn.lock"
TEMPPATH=`mktemp`

# Does WADERCONN exists?

test -f "$WADERCONN" || exit 0

# remove stalled backup file just in case
rm -f $BACKRESOLV

# get DNS addresses

PRIMARYDNS=`grep DNS1 $WADERCONN | awk {'print $2'}`
SECONDARYDNS=`grep DNS2 $WADERCONN | awk {'print $2'}`

create_resolvconf()
{
    # we are going to back up resolv.conf
    mv $RESOLVCONF $BACKRESOLV

    # create new resolv.conf
    cat >> $TEMPATH <<-EOA
    nameserver $PRIMARYDNS
    nameserver $SECONDARYDNS
    EOA
    mv $TEMPPATH $RESOLVCONF
    # in Fedora 7 umask leaves /etc/resolv.conf as 0600
    chmod 644 $RESOLVCONF
}

create_resolvconf
# restart nscd because resolv.conf has changed
if [ -e /var/run/nscd.pid ]; then
    /etc/init.d/nscd restart || true
fi

exit 0
